apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-datas
  labels:
    app: postgres-datas
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
