#beware secret must be created before deployment
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: standard
type: Opaque #default type for arbitrary key value
data:
#secret is encoded in base64 echo -n 'admin' | base64
    postgres-root-username: YWRtaW4= #need to create base64 value
    postgres-root-password: cG9zdGdyZXM= #postgres
