apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi.fullname" . }}
  labels:
    app: {{ .Values.podLabels }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}       
      targetPort: {{ .Values.service.ports.targetPort}}
      name: http
      protocol: TCP
  selector:
    app: {{ .Values.service.selector }}

