apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.postgres.secret.name }} 
    namespace: {{ .Values.postgres.namespace }} 
    labels:
    group: {{ .Values.postgres.group }}
type: {{ .Values.postgres.secret.type }} #Opaque #default type for arbitrary key value
data:
{{- range .Values.postgres.secret.data }}
  {{ .key }}: {{ .value }}
{{- end}}
