apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin-runix.fullname" . }}
  labels:
    {{- include "pgadmin-runix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgadmin-fastapi
      protocol: TCP
      name: pgadmin-fastapi
  selector:
    {{- include "pgadmin-runix.selectorLabels" . | nindent 4 }}
